import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "sw" | "fr" | "am" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LANGUAGE_LABELS: Record<Language, string> = {
  en: "English",
  sw: "Kiswahili",
  fr: "Français",
  am: "አማርኛ",
  ar: "العربية",
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // App
    "app.name": "CropGuard AI",
    "app.tagline": "Intelligent Crop Health System",

    // Nav
    "nav.home": "Home",
    "nav.map": "Map",
    "nav.scan": "Scan",
    "nav.history": "History",

    // Home
    "home.scanTitle": "Scan Your Crop",
    "home.scanDesc": "Detect diseases, get treatment costs & prevention tips",
    "home.diseaseRiskAlerts": "Disease Risk Alerts",
    "home.checkingRisk": "Checking disease risk conditions…",
    "home.diseasesReported": "disease(s) reported nearby this week",
    "home.tapToView": "Tap to view community disease map",
    "home.crops": "Crops",
    "home.diseases": "Diseases",
    "home.accuracy": "Accuracy",
    "home.howItWorks": "How It Works",
    "home.step1Title": "Capture",
    "home.step1Desc": "Take a clear photo of the affected leaf",
    "home.step2Title": "Analyse",
    "home.step2Desc": "AI analyses image + local weather conditions",
    "home.step3Title": "Diagnose",
    "home.step3Desc": "Get diagnosis, treatment costs & prevention tips",
    "home.step4Title": "Alert",
    "home.step4Desc": "Community gets warned of nearby outbreaks",
    "home.supportedCrops": "Supported Crops",
    "home.riskOn": "risk on",

    // Crop categories
    "crops.cereals": "🌾 Cereals",
    "crops.legumes": "🫘 Legumes",
    "crops.tubers": "🥔 Tubers",
    "crops.vegetables": "🥬 Vegetables",
    "crops.fruits": "🍌 Fruits",
    "crops.oilCrops": "🌻 Oil Crops",
    "crops.stimulants": "☕ Stimulants",
    "crops.fibre": "🧵 Fibre Crops",
    "crops.sugar": "🍬 Sugar Crops",
    "crops.spices": "🌶️ Spices",

    // Scan
    "scan.title": "Scan Crop Leaf",
    "scan.subtitle": "Take or upload a clear photo of the affected leaf",
    "scan.takePhoto": "Take Photo",
    "scan.takePhotoDesc": "Use your camera to capture a leaf",
    "scan.uploadImage": "Upload Image",
    "scan.uploadImageDesc": "Choose a photo from your gallery",
    "scan.tips": "Tips for Best Results",
    "scan.tip1": "Photograph a single leaf against a plain background",
    "scan.tip2": "Ensure good lighting — natural daylight works best",
    "scan.tip3": "Include both healthy and affected areas of the leaf",
    "scan.tip4": "Keep the camera steady to avoid blurry images",
    "scan.cropType": "Crop Type",
    "scan.autoDetect": "Auto-detect",
    "scan.searchCrops": "Search crops…",
    "scan.noCropsFound": "No crops found",
    "scan.selectCropHint": "Select your crop or leave as auto-detect",
    "scan.analysing": "Analysing leaf with AI…",
    "scan.analysingWait": "This may take a few seconds…",
    "scan.analyseLeaf": "Analyse Leaf",

    // Results
    "results.newScan": "New Scan",
    "results.healthy": "Healthy",
    "results.healthyPlant": "Healthy Plant",
    "results.diseaseDetected": "Disease Detected",
    "results.confidence": "Confidence",
    "results.crop": "Crop",
    "results.severity": "Severity",
    "results.careTips": "Care Tips",
    "results.treatment": "Recommended Treatment",
    "results.treatmentCost": "Estimated Treatment Cost",
    "results.totalCost": "Total Estimated Cost",
    "results.prevention": "Prevention",
    "results.scanAnother": "Scan Another",
    "results.viewHistory": "View History",
    "results.noResults": "No scan results. Please scan a leaf first.",
    "results.goToScan": "Go to Scan",

    // History
    "history.title": "Scan History",
    "history.subtitle": "Your recent crop scans and diagnoses",
    "history.noScans": "No scans yet. Try scanning a leaf!",

    // Map
    "map.title": "Community Disease Map",
    "map.subtitle": "Disease reports from farmers in the last 14 days",
    "map.diseasesReported": "Diseases Reported",
    "map.healthyScans": "Healthy Scans",
    "map.recentReports": "Recent Disease Reports",
    "map.home": "Home",

    // Language
    "lang.select": "Language",

    // Errors
    "error.analysisError": "Analysis Error",
    "error.somethingWrong": "Something went wrong",
    "error.tryAgain": "Please try again",
  },

  sw: {
    "app.name": "CropGuard AI",
    "app.tagline": "Mfumo wa Akili wa Afya ya Mazao",
    "nav.home": "Nyumbani",
    "nav.map": "Ramani",
    "nav.scan": "Piga",
    "nav.history": "Historia",
    "home.scanTitle": "Piga Picha ya Zao Lako",
    "home.scanDesc": "Gundua magonjwa, pata gharama za matibabu na ushauri wa kuzuia",
    "home.diseaseRiskAlerts": "Tahadhari za Hatari ya Magonjwa",
    "home.checkingRisk": "Inakagua hali za hatari ya magonjwa…",
    "home.diseasesReported": "magonjwa yameripotiwa jirani wiki hii",
    "home.tapToView": "Gusa kuona ramani ya magonjwa ya jamii",
    "home.crops": "Mazao",
    "home.diseases": "Magonjwa",
    "home.accuracy": "Usahihi",
    "home.howItWorks": "Jinsi Inavyofanya Kazi",
    "home.step1Title": "Piga Picha",
    "home.step1Desc": "Piga picha wazi ya jani lililoathiriwa",
    "home.step2Title": "Changanua",
    "home.step2Desc": "AI inachunguza picha + hali ya hewa ya eneo",
    "home.step3Title": "Tambua",
    "home.step3Desc": "Pata utambuzi, gharama za matibabu na ushauri",
    "home.step4Title": "Tahadhari",
    "home.step4Desc": "Jamii inaonywa kuhusu magonjwa ya karibu",
    "home.supportedCrops": "Mazao Yanayoungwa Mkono",
    "home.riskOn": "hatari kwa",
    "crops.cereals": "🌾 Nafaka",
    "crops.legumes": "🫘 Mikunde",
    "crops.tubers": "🥔 Mizizi",
    "crops.vegetables": "🥬 Mboga",
    "crops.fruits": "🍌 Matunda",
    "crops.oilCrops": "🌻 Mazao ya Mafuta",
    "crops.stimulants": "☕ Vinywaji",
    "crops.fibre": "🧵 Mazao ya Nyuzi",
    "crops.sugar": "🍬 Mazao ya Sukari",
    "crops.spices": "🌶️ Viungo",
    "scan.title": "Piga Picha ya Jani",
    "scan.subtitle": "Piga au pakia picha wazi ya jani lililoathiriwa",
    "scan.takePhoto": "Piga Picha",
    "scan.takePhotoDesc": "Tumia kamera yako kunasa jani",
    "scan.uploadImage": "Pakia Picha",
    "scan.uploadImageDesc": "Chagua picha kutoka kwenye galeri yako",
    "scan.tips": "Vidokezo kwa Matokeo Bora",
    "scan.tip1": "Piga picha ya jani moja kwenye uso tambarare",
    "scan.tip2": "Hakikisha mwanga mzuri — mwanga wa asili ni bora",
    "scan.tip3": "Jumuisha sehemu zenye afya na zilizoathirika za jani",
    "scan.tip4": "Shika kamera imara kuepuka picha zilizo blur",
    "scan.cropType": "Aina ya Zao",
    "scan.autoDetect": "Tambua Kiotomatiki",
    "scan.searchCrops": "Tafuta mazao…",
    "scan.noCropsFound": "Hakuna mazao yaliyopatikana",
    "scan.selectCropHint": "Chagua zao lako au acha kutambua kiotomatiki",
    "scan.analysing": "Inachunguza jani kwa AI…",
    "scan.analysingWait": "Hii inaweza kuchukua sekunde chache…",
    "scan.analyseLeaf": "Changanua Jani",
    "results.newScan": "Upigaji Mpya",
    "results.healthy": "Afya Njema",
    "results.healthyPlant": "Mmea Wenye Afya",
    "results.diseaseDetected": "Ugonjwa Umetambuliwa",
    "results.confidence": "Uhakika",
    "results.crop": "Zao",
    "results.severity": "Ukali",
    "results.careTips": "Ushauri wa Utunzaji",
    "results.treatment": "Matibabu Yanayopendekezwa",
    "results.treatmentCost": "Gharama ya Matibabu Inayokadiriwa",
    "results.totalCost": "Gharama Yote Inayokadiriwa",
    "results.prevention": "Kuzuia",
    "results.scanAnother": "Piga Picha Nyingine",
    "results.viewHistory": "Tazama Historia",
    "results.noResults": "Hakuna matokeo. Tafadhali piga picha ya jani kwanza.",
    "results.goToScan": "Nenda Kupiga Picha",
    "history.title": "Historia ya Upigaji",
    "history.subtitle": "Upigaji picha na utambuzi wako wa hivi karibuni",
    "history.noScans": "Hakuna picha zilizopigwa bado. Jaribu kupiga picha ya jani!",
    "map.title": "Ramani ya Magonjwa ya Jamii",
    "map.subtitle": "Ripoti za magonjwa kutoka kwa wakulima katika siku 14 zilizopita",
    "map.diseasesReported": "Magonjwa Yaliyoripotiwa",
    "map.healthyScans": "Picha za Afya",
    "map.recentReports": "Ripoti za Hivi Karibuni za Magonjwa",
    "map.home": "Nyumbani",
    "lang.select": "Lugha",
    "error.analysisError": "Hitilafu ya Uchambuzi",
    "error.somethingWrong": "Kuna kitu kimeenda vibaya",
    "error.tryAgain": "Tafadhali jaribu tena",
  },

  fr: {
    "app.name": "CropGuard AI",
    "app.tagline": "Système Intelligent de Santé des Cultures",
    "nav.home": "Accueil",
    "nav.map": "Carte",
    "nav.scan": "Scanner",
    "nav.history": "Historique",
    "home.scanTitle": "Scannez Votre Culture",
    "home.scanDesc": "Détectez les maladies, obtenez les coûts de traitement et des conseils de prévention",
    "home.diseaseRiskAlerts": "Alertes de Risque de Maladie",
    "home.checkingRisk": "Vérification des conditions de risque…",
    "home.diseasesReported": "maladie(s) signalée(s) à proximité cette semaine",
    "home.tapToView": "Appuyez pour voir la carte des maladies communautaires",
    "home.crops": "Cultures",
    "home.diseases": "Maladies",
    "home.accuracy": "Précision",
    "home.howItWorks": "Comment Ça Marche",
    "home.step1Title": "Capturer",
    "home.step1Desc": "Prenez une photo claire de la feuille affectée",
    "home.step2Title": "Analyser",
    "home.step2Desc": "L'IA analyse l'image + les conditions météo locales",
    "home.step3Title": "Diagnostiquer",
    "home.step3Desc": "Obtenez le diagnostic, les coûts et les conseils de prévention",
    "home.step4Title": "Alerter",
    "home.step4Desc": "La communauté est alertée des épidémies proches",
    "home.supportedCrops": "Cultures Supportées",
    "home.riskOn": "risque sur",
    "crops.cereals": "🌾 Céréales",
    "crops.legumes": "🫘 Légumineuses",
    "crops.tubers": "🥔 Tubercules",
    "crops.vegetables": "🥬 Légumes",
    "crops.fruits": "🍌 Fruits",
    "crops.oilCrops": "🌻 Oléagineux",
    "crops.stimulants": "☕ Stimulants",
    "crops.fibre": "🧵 Cultures Fibreuses",
    "crops.sugar": "🍬 Cultures Sucrières",
    "crops.spices": "🌶️ Épices",
    "scan.title": "Scanner une Feuille",
    "scan.subtitle": "Prenez ou téléchargez une photo claire de la feuille affectée",
    "scan.takePhoto": "Prendre une Photo",
    "scan.takePhotoDesc": "Utilisez votre caméra pour capturer une feuille",
    "scan.uploadImage": "Télécharger une Image",
    "scan.uploadImageDesc": "Choisissez une photo de votre galerie",
    "scan.tips": "Conseils pour de Meilleurs Résultats",
    "scan.tip1": "Photographiez une seule feuille sur un fond uni",
    "scan.tip2": "Assurez un bon éclairage — la lumière naturelle est idéale",
    "scan.tip3": "Incluez les zones saines et affectées de la feuille",
    "scan.tip4": "Gardez l'appareil stable pour éviter les images floues",
    "scan.cropType": "Type de Culture",
    "scan.autoDetect": "Détection Auto",
    "scan.searchCrops": "Rechercher des cultures…",
    "scan.noCropsFound": "Aucune culture trouvée",
    "scan.selectCropHint": "Sélectionnez votre culture ou laissez en détection auto",
    "scan.analysing": "Analyse de la feuille par IA…",
    "scan.analysingWait": "Cela peut prendre quelques secondes…",
    "scan.analyseLeaf": "Analyser la Feuille",
    "results.newScan": "Nouveau Scan",
    "results.healthy": "Sain",
    "results.healthyPlant": "Plante Saine",
    "results.diseaseDetected": "Maladie Détectée",
    "results.confidence": "Confiance",
    "results.crop": "Culture",
    "results.severity": "Sévérité",
    "results.careTips": "Conseils d'Entretien",
    "results.treatment": "Traitement Recommandé",
    "results.treatmentCost": "Coût Estimé du Traitement",
    "results.totalCost": "Coût Total Estimé",
    "results.prevention": "Prévention",
    "results.scanAnother": "Scanner une Autre",
    "results.viewHistory": "Voir l'Historique",
    "results.noResults": "Aucun résultat. Veuillez d'abord scanner une feuille.",
    "results.goToScan": "Aller au Scanner",
    "history.title": "Historique des Scans",
    "history.subtitle": "Vos scans et diagnostics récents",
    "history.noScans": "Aucun scan encore. Essayez de scanner une feuille !",
    "map.title": "Carte Communautaire des Maladies",
    "map.subtitle": "Rapports de maladies des agriculteurs des 14 derniers jours",
    "map.diseasesReported": "Maladies Signalées",
    "map.healthyScans": "Scans Sains",
    "map.recentReports": "Rapports Récents de Maladies",
    "map.home": "Accueil",
    "lang.select": "Langue",
    "error.analysisError": "Erreur d'Analyse",
    "error.somethingWrong": "Quelque chose s'est mal passé",
    "error.tryAgain": "Veuillez réessayer",
  },

  am: {
    "app.name": "CropGuard AI",
    "app.tagline": "ብልጥ የሰብል ጤና ስርዓት",
    "nav.home": "መነሻ",
    "nav.map": "ካርታ",
    "nav.scan": "ቃኝ",
    "nav.history": "ታሪክ",
    "home.scanTitle": "ሰብልዎን ቃኙ",
    "home.scanDesc": "በሽታዎችን ይለዩ፣ የሕክምና ወጪዎች እና የመከላከያ ምክሮች ያግኙ",
    "home.diseaseRiskAlerts": "የበሽታ አደጋ ማስጠንቀቂያዎች",
    "home.checkingRisk": "የበሽታ አደጋ ሁኔታዎችን በመፈተሽ ላይ…",
    "home.diseasesReported": "በሽታ(ዎች) በአቅራቢያ በዚህ ሳምንት ተዘግበዋል",
    "home.tapToView": "የማህበረሰብ የበሽታ ካርታን ለማየት ንኩ",
    "home.crops": "ሰብሎች",
    "home.diseases": "በሽታዎች",
    "home.accuracy": "ትክክለኛነት",
    "home.howItWorks": "እንዴት ይሰራል",
    "home.step1Title": "አንሳ",
    "home.step1Desc": "የተጎዳውን ቅጠል ግልጽ ፎቶ አንሱ",
    "home.step2Title": "ተንትን",
    "home.step2Desc": "AI ምስሉን + የአካባቢ የአየር ሁኔታን ይተነትናል",
    "home.step3Title": "ምርመራ",
    "home.step3Desc": "ምርመራ፣ የሕክምና ወጪዎች እና ምክሮች ያግኙ",
    "home.step4Title": "ማስጠንቀቂያ",
    "home.step4Desc": "ማህበረሰቡ ስለ አቅራቢያ ወረርሽኞች ይጠነቀቃል",
    "home.supportedCrops": "የሚደገፉ ሰብሎች",
    "home.riskOn": "አደጋ በ",
    "crops.cereals": "🌾 እህሎች",
    "crops.legumes": "🫘 ጥራጥሬዎች",
    "crops.tubers": "🥔 ስር ሰብሎች",
    "crops.vegetables": "🥬 አትክልቶች",
    "crops.fruits": "🍌 ፍራፍሬዎች",
    "crops.oilCrops": "🌻 የዘይት ሰብሎች",
    "crops.stimulants": "☕ የመነቃቃት ሰብሎች",
    "crops.fibre": "🧵 የፋይበር ሰብሎች",
    "crops.sugar": "🍬 የስኳር ሰብሎች",
    "crops.spices": "🌶️ ቅመማ ቅመሞች",
    "scan.title": "የቅጠል ቅጂ ቃኝ",
    "scan.subtitle": "የተጎዳውን ቅጠል ግልጽ ፎቶ አንሱ ወይም ያስገቡ",
    "scan.takePhoto": "ፎቶ አንሳ",
    "scan.takePhotoDesc": "ቅጠል ለመያዝ ካሜራዎን ይጠቀሙ",
    "scan.uploadImage": "ምስል ያስገቡ",
    "scan.uploadImageDesc": "ከማዕከለ-ስዕላትዎ ፎቶ ይምረጡ",
    "scan.tips": "ለምርጥ ውጤቶች ምክሮች",
    "scan.tip1": "በቀላል ዳራ ላይ አንድ ቅጠል ፎቶ ያንሱ",
    "scan.tip2": "ጥሩ ብርሃን ያረጋግጡ — ተፈጥሯዊ ብርሃን በጣም ጥሩ ነው",
    "scan.tip3": "ጤናማ እና የተጎዱ ቦታዎችን ያካትቱ",
    "scan.tip4": "ብዥ ያለ ምስል ለማስቀረት ካሜራውን ያረጋጉ",
    "scan.cropType": "የሰብል ዓይነት",
    "scan.autoDetect": "ራስ-ሰር ለይ",
    "scan.searchCrops": "ሰብሎችን ፈልግ…",
    "scan.noCropsFound": "ሰብሎች አልተገኙም",
    "scan.selectCropHint": "ሰብልዎን ይምረጡ ወይም ራስ-ሰር ይተውት",
    "scan.analysing": "ቅጠሉን በ AI በመተንተን ላይ…",
    "scan.analysingWait": "ይህ ጥቂት ሰከንዶች ሊወስድ ይችላል…",
    "scan.analyseLeaf": "ቅጠሉን ተንትን",
    "results.newScan": "አዲስ ቃኝ",
    "results.healthy": "ጤናማ",
    "results.healthyPlant": "ጤናማ ተክል",
    "results.diseaseDetected": "በሽታ ተገኝቷል",
    "results.confidence": "እምነት",
    "results.crop": "ሰብል",
    "results.severity": "ክብደት",
    "results.careTips": "የእንክብካቤ ምክሮች",
    "results.treatment": "የሚመከር ሕክምና",
    "results.treatmentCost": "የተገመተ የሕክምና ወጪ",
    "results.totalCost": "ጠቅላላ የተገመተ ወጪ",
    "results.prevention": "መከላከል",
    "results.scanAnother": "ሌላ ቃኝ",
    "results.viewHistory": "ታሪክ ተመልከት",
    "results.noResults": "ምንም ውጤት የለም። እባክዎ መጀመሪያ ቅጠል ይቃኙ።",
    "results.goToScan": "ወደ ቃኝ ሂድ",
    "history.title": "የቃኝ ታሪክ",
    "history.subtitle": "የቅርብ ጊዜ ቃኝዎችዎ እና ምርመራዎች",
    "history.noScans": "እስካሁን ቃኝ የለም። ቅጠል ለመቃኘት ይሞክሩ!",
    "map.title": "የማህበረሰብ የበሽታ ካርታ",
    "map.subtitle": "ከአርሶ አደሮች የመጡ የበሽታ ዘገባዎች ባለፉት 14 ቀናት",
    "map.diseasesReported": "የተዘገቡ በሽታዎች",
    "map.healthyScans": "ጤናማ ቃኝዎች",
    "map.recentReports": "የቅርብ ጊዜ የበሽታ ዘገባዎች",
    "map.home": "መነሻ",
    "lang.select": "ቋንቋ",
    "error.analysisError": "የትንተና ስህተት",
    "error.somethingWrong": "የሆነ ችግር ተፈጥሯል",
    "error.tryAgain": "እባክዎ እንደገና ይሞክሩ",
  },

  ar: {
    "app.name": "CropGuard AI",
    "app.tagline": "نظام ذكي لصحة المحاصيل",
    "nav.home": "الرئيسية",
    "nav.map": "الخريطة",
    "nav.scan": "مسح",
    "nav.history": "السجل",
    "home.scanTitle": "امسح محصولك",
    "home.scanDesc": "اكتشف الأمراض واحصل على تكاليف العلاج ونصائح الوقاية",
    "home.diseaseRiskAlerts": "تنبيهات مخاطر الأمراض",
    "home.checkingRisk": "جارٍ فحص ظروف مخاطر الأمراض…",
    "home.diseasesReported": "مرض(أمراض) تم الإبلاغ عنها بالقرب هذا الأسبوع",
    "home.tapToView": "اضغط لعرض خريطة أمراض المجتمع",
    "home.crops": "محاصيل",
    "home.diseases": "أمراض",
    "home.accuracy": "الدقة",
    "home.howItWorks": "كيف يعمل",
    "home.step1Title": "التقط",
    "home.step1Desc": "التقط صورة واضحة للورقة المصابة",
    "home.step2Title": "حلل",
    "home.step2Desc": "يحلل الذكاء الاصطناعي الصورة + ظروف الطقس المحلية",
    "home.step3Title": "شخّص",
    "home.step3Desc": "احصل على التشخيص وتكاليف العلاج ونصائح الوقاية",
    "home.step4Title": "نبّه",
    "home.step4Desc": "يتم تحذير المجتمع من تفشي الأمراض القريبة",
    "home.supportedCrops": "المحاصيل المدعومة",
    "home.riskOn": "خطر على",
    "crops.cereals": "🌾 حبوب",
    "crops.legumes": "🫘 بقوليات",
    "crops.tubers": "🥔 درنيات",
    "crops.vegetables": "🥬 خضروات",
    "crops.fruits": "🍌 فواكه",
    "crops.oilCrops": "🌻 محاصيل زيتية",
    "crops.stimulants": "☕ منبهات",
    "crops.fibre": "🧵 محاصيل ألياف",
    "crops.sugar": "🍬 محاصيل سكرية",
    "crops.spices": "🌶️ توابل",
    "scan.title": "امسح ورقة المحصول",
    "scan.subtitle": "التقط أو ارفع صورة واضحة للورقة المصابة",
    "scan.takePhoto": "التقط صورة",
    "scan.takePhotoDesc": "استخدم الكاميرا لالتقاط ورقة",
    "scan.uploadImage": "ارفع صورة",
    "scan.uploadImageDesc": "اختر صورة من معرض الصور",
    "scan.tips": "نصائح لأفضل النتائج",
    "scan.tip1": "صوّر ورقة واحدة على خلفية بسيطة",
    "scan.tip2": "تأكد من الإضاءة الجيدة — ضوء النهار الطبيعي هو الأفضل",
    "scan.tip3": "قم بتضمين المناطق السليمة والمصابة من الورقة",
    "scan.tip4": "حافظ على ثبات الكاميرا لتجنب الصور الضبابية",
    "scan.cropType": "نوع المحصول",
    "scan.autoDetect": "كشف تلقائي",
    "scan.searchCrops": "ابحث عن محاصيل…",
    "scan.noCropsFound": "لم يتم العثور على محاصيل",
    "scan.selectCropHint": "اختر محصولك أو اتركه للكشف التلقائي",
    "scan.analysing": "جارٍ تحليل الورقة بالذكاء الاصطناعي…",
    "scan.analysingWait": "قد يستغرق هذا بضع ثوانٍ…",
    "scan.analyseLeaf": "حلل الورقة",
    "results.newScan": "مسح جديد",
    "results.healthy": "سليم",
    "results.healthyPlant": "نبات سليم",
    "results.diseaseDetected": "تم اكتشاف مرض",
    "results.confidence": "الثقة",
    "results.crop": "المحصول",
    "results.severity": "الشدة",
    "results.careTips": "نصائح العناية",
    "results.treatment": "العلاج الموصى به",
    "results.treatmentCost": "تكلفة العلاج المقدرة",
    "results.totalCost": "التكلفة الإجمالية المقدرة",
    "results.prevention": "الوقاية",
    "results.scanAnother": "امسح أخرى",
    "results.viewHistory": "عرض السجل",
    "results.noResults": "لا توجد نتائج. يرجى مسح ورقة أولاً.",
    "results.goToScan": "اذهب للمسح",
    "history.title": "سجل المسح",
    "history.subtitle": "عمليات المسح والتشخيص الأخيرة",
    "history.noScans": "لا يوجد مسح بعد. جرب مسح ورقة!",
    "map.title": "خريطة أمراض المجتمع",
    "map.subtitle": "تقارير الأمراض من المزارعين في آخر 14 يوماً",
    "map.diseasesReported": "أمراض مُبلَّغ عنها",
    "map.healthyScans": "عمليات مسح سليمة",
    "map.recentReports": "تقارير الأمراض الأخيرة",
    "map.home": "الرئيسية",
    "lang.select": "اللغة",
    "error.analysisError": "خطأ في التحليل",
    "error.somethingWrong": "حدث خطأ ما",
    "error.tryAgain": "يرجى المحاولة مرة أخرى",
  },
};

export { LANGUAGE_LABELS };

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("cropguard-lang");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("cropguard-lang", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const isRTL = language === "ar";

  useEffect(() => {
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
